### ISSUE TITLE
Access rights

### ISSUE THREAD

**Issue by gdalle** [adrien-le-franc/JuliaHPC-Cermics#7]
Hi @adrien-le-franc!
I tried to push my first file and it seems I don't have access rights to the repo, could you maybe fix that?
Thx

**Comment by adrien-le-franc** [comment]
Hi Guillaume, your invitation to collaborate is still pending, you need to accept it to have all accesses to the repo: check your mails or maybe you can reach this link https://github.com/adrien-le-franc/JuliaHPC-Cemrics/invitations ?

**Comment by gdalle** [comment]
Apparently the invitation expired since I did not accept it right away...

**Comment by adrien-le-franc** [comment]
ok, I just re-sent the invitation, you can close the issue if you could join us
